import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import os

def plot_monte_carlo(csv_filename):
    # Get the project root directory (one level up from this script)
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    csv_path = os.path.join(root_dir, csv_filename)
    output_image = os.path.join(root_dir, "data", "monte_carlo_viz.png")

    # Load the data generated by our C++ engine
    try:
        df = pd.read_csv(csv_path)
    except FileNotFoundError:
        print(f"Error: {csv_path} not found. Did you run the C++ engine first?")
        return

    # Create a figure with two subplots: Path plot and Final Distribution Histogram
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6), gridspec_kw={'width_ratios': [3, 1]})
    
    # 1. Spaghetti Plot (The Paths)
    # We use a low 'alpha' (transparency) so we can see the density of paths
    ax1.plot(df, color='royalblue', alpha=0.1, linewidth=1)
    
    # Highlight the 'Average' path in bold black
    ax1.plot(df.mean(axis=1), color='black', linewidth=2, label='Mean Path')
    
    ax1.set_title("Monte Carlo Asset Paths (GBM Simulation)", fontsize=14, fontweight='bold')
    ax1.set_xlabel("Trading Days (Steps)", fontsize=12)
    ax1.set_ylabel("Asset Price ($)", fontsize=12)
    ax1.grid(True, linestyle='--', alpha=0.6)
    ax1.legend()

    # 2. Histogram (The Final Distribution)
    final_prices = df.iloc[-1, :]
    ax2.hist(final_prices, bins=30, orientation='horizontal', color='royalblue', alpha=0.7, edgecolor='white')
    
    # Add a horizontal line for the Mean
    ax2.axhline(final_prices.mean(), color='black', linestyle='--', linewidth=2)
    
    ax2.set_title("Final Price Distribution", fontsize=12)
    ax2.set_xlabel("Frequency", fontsize=10)
    ax2.get_yaxis().set_visible(False) # Hide Y-axis for the histogram as it shares scale with the paths
    ax2.grid(axis='x', linestyle='--', alpha=0.6)

    plt.tight_layout()
    
    # Save for the portfolio
    output_image = "data/monte_carlo_viz.png"
    plt.savefig(output_image, dpi=300)
    print(f"Visualization saved to: {output_image}")
    
    # Show the plot
    plt.show()

if __name__ == "__main__":
    plot_monte_carlo("data/sample_paths.csv")
